apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator
  namespace: liveclass
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulator
  template:
    metadata:
      labels:
        app: simulator
    spec:
      containers:
        - name: simulator
          image: liveclass/simulator:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: simulator-config
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
